### PR TITLE
[WIP] Bump version and adjust to Cirq 0.6.0

### PR DESCRIPTION
**Pull request by johannesjmeyer**
Bump the version to 0.2.0-dev and introduce a changelog

Fix errors introduced by Cirq going from 0.5.0 to 0.6.0

### CODE REVIEW

**Comment by co9olguy** [comment]
@johannesjmeyer what's left to fix here? Anything another dev could help with to push over the line?

**Comment by johannesjmeyer** [comment]
I need some input from a person familiar with Travis here. The tests fail due to version clashes and I don't really understand where this comes from.
________________________________

**Comment by josh146** [comment]
(Cirq doesn't support 3.5 any more it seems, so I've removed it from Travis)

**Comment by johannesjmeyer** [comment]
Thanks Josh!

**Pull request merged**
